### ISSUE TITLE
Enchants not showing up?

### ISSUE THREAD

**Issue by nonlooped** [kr45732/rust-query-api#82]

**Comment by kr45732** [comment]
I need more information. Is this in the query endpoint? If I remember correctly, currently enchants only show up if the item is an enchanted book but I can (and probably should) change one line of code so it shows up on all items. Is that what you are referring to?

**Comment by nonlooped** [comment]
> I need more information. Is this in the query endpoint? If I remember correctly, currently enchants only show up if the item is an enchanted book but I can (and probably should) change one line of code so it shows up on all items. Is that what you are referring to?

Yes it is exactly what I'm referring to.
