### ISSUE TITLE
Average_Bin & Average_auction not sending data

### ISSUE THREAD

**Issue by 1tzkaos** [kr45732/rust-query-api#85]
Hello, I am having trouble with the average endpoints. Whenever called, they respond with an empty object {}. I started the API an hour ago but was only querying 20 minutes ago to present. Does the API need to be running for longer? I Checked the Database, and it just shows {} next to each UNIX timestamp

Thank you for your time

**Comment by kr45732** [comment]
Can you try using the latest commit in [this branch](https://github.com/kr45732/rust-query-api/tree/patch-averages) and let me know if it works

**Comment by 1tzkaos** [comment]
> Can you try using the latest commit in [this branch](https://github.com/kr45732/rust-query-api/tree/patch-averages) and let me know if it works

Yep that seemed to fix it! Thank you very much
